mxm_wifiex: fix build error for 64-bit division
When build on 32-bit platform, error log shows:
ERROR: modpost: "__aeabi_uldivmod" [mwifiex/mlan.ko] undefined!
ERROR: modpost: "__aeabi_ldivmod" [mwifiex/mlan.ko] undefined!

32-bit platform need to use do_div() to support 64-bit division.

Signed-off-by: Luke Wang <ziniu.wang_1@nxp.com>