mxm_wifiex: fix L6.9 kernel next tree build errors
When building the wifi driver based on L6.9 kernel next tree, will
observe the following build errors.
These errors are caused by kernel patch 490a79faf95e("net: introduce
include/net/rps.h"), which moves RPS related structures and helpers from
include/linux/netdevice.h and include/net/sock.h to a new include file.
So needs to make corresponding changes in wifi driver to avoid the
build break.

/mxm_wifiex/wlan_src/mlinux/moal_main.c: In function 'woal_set_rps_map':
/mxm_wifiex/wlan_src/mlinux/moal_main.c:3744:43: error: implicit declaration of function 'RPS_MAP_SIZE'; did you mean 'XPS_MAP_SIZE'? [-Werror=implicit-function-declaration]
3744 |         map = kzalloc(max_t(unsigned int, RPS_MAP_SIZE(cpumask_weight(mask)),
......
/mxm_wifiex/wlan_src/mlinux/moal_main.c:3773:36: error: 'rps_needed' undeclared (first use in this function)
3773 |                 static_branch_inc(&rps_needed);

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>