mxm_wifiex: fix L6.8 kernel next tree build errors -- cfg80211_ch_switch_notify
When building the wifi driver based on L6.8 kernel next tree, will
observe the following build errors.
These errors are caused by kernel patch b82730bf57b5("wifi:
cfg80211/mac80211: move puncturing into chandef"), which moves
puncturing into chandef and deletes the fourth parameter punct_bitmap of
function cfg80211_ch_switch_notify(), here change the code accordingly
to avoid the build break.

/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c: In function ‘moal_recv_event’:
/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c:3911:25: error: too many arguments to function ‘cfg80211_ch_switch_notify’
 3911 |                         cfg80211_ch_switch_notify(priv->netdev, &priv->chan, 0,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /mwifiex/mxm_wifiex/wlan_src/mlinux/moal_main.h:130,
                 from /mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.c:28:
./include/net/cfg80211.h:8759:6: note: declared here
 8759 | void cfg80211_ch_switch_notify(struct net_device *dev,
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:244: /mwifiex/mxm_wifiex/wlan_src/mlinux/moal_shim.o] Error 1
make[3]: *** Waiting for unfinished jobs....
/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_cfg80211.c: In function ‘woal_cfg80211_notify_channel’:
/mwifiex/mxm_wifiex/wlan_src/mlinux/moal_cfg80211.c:5175:17: error: too many arguments to function ‘cfg80211_ch_switch_notify’
 5175 |                 cfg80211_ch_switch_notify(priv->netdev, &chandef, 0, 0);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~
...

Signed-off-by: Sherry Sun <sherry.sun@nxp.com>